
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace HeartyBase.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            HeartyBase.ModelInput sampleData = new HeartyBase.ModelInput()
            {
                BMI = 16.6F,
                AlcoholDrinking = @"No",
                PhysicalHealth = 3F,
                MentalHealth = 30F,
                Sex = @"Female",
                AgeCategory = @"55-59",
                GenHealth = @"Very good",
                SleepTime = 5F,
            };

            Console.WriteLine("Using model to make single prediction -- Comparing actual HeartDisease with predicted HeartDisease from sample data...\n\n");


            Console.WriteLine($"BMI: {16.6F}");
            Console.WriteLine($"AlcoholDrinking: {@"No"}");
            Console.WriteLine($"PhysicalHealth: {3F}");
            Console.WriteLine($"MentalHealth: {30F}");
            Console.WriteLine($"Sex: {@"Female"}");
            Console.WriteLine($"AgeCategory: {@"55-59"}");
            Console.WriteLine($"GenHealth: {@"Very good"}");
            Console.WriteLine($"SleepTime: {5F}");



            // Use the model and Prediction Engine to predict on new sample data
            var predictionResult = predEngine.Predict(sampleData);

            Console.WriteLine($"\n\nPredicted Sentiment: {predictionResult.PredictedLabel}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
